"""
Django settings for cenit project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import json

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# credentials
credentials_path = os.path.join(BASE_DIR, 'admin.json')

# credentials config from json
with open(credentials_path, encoding='utf-8') as f:
    db_config = json.load(f)

MONGODB_URI = db_config.pop("MONGODB_URI", "mongodb://localhost:27017/")
MONGODB_NAME = db_config.pop("MONGODB_NAME", "Cenit")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--cwlz%m75z$h@en@a736j!=qo3b(qdjhjivt9$+1f005f+s%8p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'catalogo',
    'suscripciones',
    'usuarios',
    'reproductor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'usuarios.middleware.RoleRestrictionMiddleware',
]

ROOT_URLCONF = 'cenit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # <--- Crucial
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuarios.context_processors.user_role',
            ],
        },
    },
]

WSGI_APPLICATION = 'cenit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Al loguearse, va directo al catálogo
LOGIN_REDIRECT_URL = 'catalog_overview'

# Si intenta entrar a una ruta protegida sin loguearse, lo manda al login personalizado
LOGIN_URL = 'login'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

CREDENTIALS_FILE = os.path.join(BASE_DIR, 'spotifyCreds.json')

# Leer el JSON de credenciales
try:
    with open(CREDENTIALS_FILE) as f:
        credentials = json.load(f)
        SPOTIFY_CLIENT_ID = credentials.get('spotify_client_id')
        SPOTIFY_CLIENT_SECRET = credentials.get('spotify_client_secret')
except FileNotFoundError:
    print("Advertencia: No se encontró el archivo credentials.json")
    SPOTIFY_CLIENT_ID = None
    SPOTIFY_CLIENT_SECRET = None

# Redirecciones de Autenticación
LOGIN_URL = 'login'  # Si un usuario no autenticado intenta entrar al catálogo, lo manda aquí

# LA CLAVE DEL FLUJO: A dónde ir después de un login exitoso.
# Reemplaza 'albums_overview' por el `name` exacto de tu URL principal del catálogo.
LOGIN_REDIRECT_URL = 'songs_overview'

# A dónde ir después de cerrar sesión
LOGOUT_REDIRECT_URL = 'landing'

# Email backend configuration for local development
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'admin@cenit.com'

# Custom Authentication Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default for superusers (e.g. cenit-sa)
    'usuarios.auth_backend.MongoAuthBackend',     # Custom for MongoDB users (e.g. Sofia, Camila, Mateo)
]
